repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8