version: "3.9"
name: "eventcally-test-services"

services:
  db:
    image: postgis/postgis:12-3.1
    healthcheck:
      test: "pg_isready --username=eventcally && psql --username=eventcally --list"
      start_period: "5s"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=eventcally
      - POSTGRES_USER=eventcally
      - POSTGRES_PASSWORD=pass

  redis:
    image: bitnami/redis:6.2
    healthcheck:
      test: "redis-cli -a 'pass' ping | grep PONG"
      start_period: "5s"
    ports:
      - 6380:6379
    environment:
      REDIS_PASSWORD: pass
