name: "eventcally-test"

services:
  db:
    image: ${TEST_DB_IMAGE:-postgis/postgis:12-3.1}
    healthcheck:
      test: "pg_isready --username=eventcally && psql --username=eventcally --list"
      start_period: "5s"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=eventcally
      - POSTGRES_USER=eventcally
      - POSTGRES_PASSWORD=pass
    tmpfs:
      - /var/lib/postgresql/data
    command: postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=200

  redis:
    image: bitnami/redis:latest
    healthcheck:
      test: "redis-cli -a 'pass' ping | grep PONG"
      start_period: "5s"
    ports:
      - 6380:6379
    environment:
      REDIS_PASSWORD: pass

  limiter_redis:
    image: bitnami/redis:latest
    healthcheck:
      test: "redis-cli -a 'pass' ping | grep PONG"
      start_period: "5s"
    ports:
      - 6381:6379
    environment:
      REDIS_PASSWORD: pass

  pytest:
    build: .
    entrypoint: []
    working_dir: /app
    volumes:
      - .:/app
    profiles:
      - test
    environment:
      TEST_DB_ADMIN_URL: postgresql://eventcally:pass@db:5432/eventcally
      TEST_DB_HOST: db
      TEST_REDIS_HOST: redis
      TEST_LIMITER_REDIS_HOST: limiter_redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      limiter_redis:
        condition: service_healthy
