from abc import ABC, abstractmethod
from typing import Any

from project.domain import commands
from project.domain.abstract_unit_of_work import AbstractUnitOfWork


class AbstractCommandHandler(ABC):
    @abstractmethod
    def handle(
        self, cmd: commands.Command, uow: AbstractUnitOfWork
    ) -> Any:  # pragma: no cover
        raise NotImplementedError

    def _set_autogenerated_id(
        self, uow: AbstractUnitOfWork, event_type: type, model: Any
    ):
        event = uow.get_first_pending_event_by_type(event_type)
        event.id = model.id
