from abc import ABC, abstractmethod
from typing import Any, Optional

from project.domain import commands
from project.domain.abstract_unit_of_work import AbstractUnitOfWork
from project.models.image import Image


class AbstractCommandHandler(ABC):
    @abstractmethod
    def handle(
        self, cmd: commands.Command, uow: AbstractUnitOfWork
    ) -> Any:  # pragma: no cover
        raise NotImplementedError

    def _set_autogenerated_id(
        self, uow: AbstractUnitOfWork, event_type: type, model: Any
    ):
        event = uow.get_first_pending_event_by_type(event_type)
        event.id = model.id

    def _set_autogenerated_image_id(
        self,
        uow: AbstractUnitOfWork,
        event_type: type,
        image: Optional[Image],
        event_image_attr: str,
    ):
        if not image:
            return

        event = uow.get_first_pending_event_by_type(event_type)
        image_event = getattr(event, event_image_attr)

        if not image_event:
            return

        setattr(image_event, "id", image.id)
        setattr(image_event, "hash", image.get_hash())
