from project.domain import commands, events
from project.domain.abstract_unit_of_work import AbstractUnitOfWork
from project.models.oauth import OAuth2Client

from .abstract_command_handler import AbstractCommandHandler


class CreateAppHandler(AbstractCommandHandler):
    def handle(self, cmd: commands.CreateAppCommand, uow: AbstractUnitOfWork):
        with uow:
            app = OAuth2Client.create_app(cmd)
            uow.apps.add(app)
            uow.commit()

            self._set_autogenerated_id(uow, events.AppCreated, app)
            return commands.CreateAppCommandResult(id=app.id)
