from project.domain import commands, events
from project.domain.abstract_unit_of_work import AbstractUnitOfWork
from project.models import EventPlace

from .abstract_command_handler import AbstractCommandHandler


class CreateEventPlaceHandler(AbstractCommandHandler):
    def handle(self, cmd: commands.CreateEventPlaceCommand, uow: AbstractUnitOfWork):
        with uow:
            event_place = EventPlace.create(cmd)
            uow.event_places.add(event_place)
            uow.commit()

            self._set_autogenerated_id(uow, events.EventPlaceCreated, event_place)
            self._set_autogenerated_image_id(
                uow, events.EventPlaceCreated, event_place.photo, "photo"
            )
            return commands.CreateEventPlaceCommandResult(id=event_place.id)
