from project.domain import commands, events
from project.domain.abstract_unit_of_work import AbstractUnitOfWork
from project.models import AppInstallation

from .abstract_command_handler import AbstractCommandHandler
from .app_utils import ensure_app_exists


class InstallAppHandler(AbstractCommandHandler):
    def handle(self, cmd: commands.InstallAppCommand, uow: AbstractUnitOfWork):
        with uow:
            app = ensure_app_exists(cmd.app_id, uow)
            app_installation = AppInstallation.create_installation(cmd, app)
            uow.apps.add_app_installation(app_installation)
            uow.commit()
            self._set_autogenerated_id(
                uow, events.AppInstallationCreated, app_installation
            )
            return commands.InstallAppCommandResult(id=app_installation.id)
