"""Tests to cover remaining coverage gaps - all pure unit tests, no DB needed."""

import datetime

# ---------------------------------------------------------------------------
# container.py line 22 – get_app_logger()
# ---------------------------------------------------------------------------


def test_get_app_logger_returns_logger(app):
    with app.app_context():
        from project.container import get_app_logger

        logger = get_app_logger()
        assert logger is not None


# ---------------------------------------------------------------------------
# app_webhooks/__init__.py line 35 – return info (found path)
# ---------------------------------------------------------------------------


def test_get_app_webhook_info_returns_info_for_known_event_type():
    from project.service_layer.webhooks.app_webhooks import (
        get_app_webhook_info_by_event_type,
    )

    result = get_app_webhook_info_by_event_type("app.installed")
    assert result is not None
    assert result.event_type == "app.installed"


# ---------------------------------------------------------------------------
# abstract_command_handler.py line 36 – if not image_event: return
# ---------------------------------------------------------------------------


def test_set_autogenerated_image_id_returns_early_when_no_image_event():
    from unittest.mock import MagicMock

    from project.service_layer.command_handlers.abstract_command_handler import (
        AbstractCommandHandler,
    )

    class _ConcreteHandler(AbstractCommandHandler):
        def handle(self, cmd, uow):
            pass

    handler = _ConcreteHandler()
    uow = MagicMock()
    image = MagicMock()

    # event_image_attr points to an attribute that returns a falsy value
    event = MagicMock()
    setattr(event, "logo_event", None)
    uow.get_first_pending_event_by_type.return_value = event

    # Should return early at line 36 without error
    handler._set_autogenerated_image_id(uow, object, image, "logo_event")


# ---------------------------------------------------------------------------
# webhook_mapper_context.py lines 3-5 – get_image_url
# ---------------------------------------------------------------------------


def test_webhook_mapper_context_get_image_url(app):
    with app.test_request_context("/"):
        from project.service_layer.webhooks.webhook_mapper_context import (
            WebhookMapperContext,
        )

        ctx = WebhookMapperContext()
        url = ctx.get_image_url(1, 12345)
        assert "1" in url


# ---------------------------------------------------------------------------
# Nested payload return cls(...) lines
# ---------------------------------------------------------------------------


def test_actor_payload_from_event_with_actor():
    from project.domain.types.actor import Actor as DomainActor
    from project.service_layer.webhooks.payloads.nested.actor import Actor

    actor = DomainActor(user_id=42, app_installation_id=None)
    result = Actor.from_event(actor, ctx=None)
    assert result is not None
    assert result.user_id == 42


def test_image_created_payload_from_event_with_image(app):
    with app.test_request_context("/"):
        from project.domain.events.image_created import (
            ImageCreated as ImageCreatedEvent,
        )
        from project.service_layer.webhooks.payloads.nested.image_created import (
            ImageCreated,
        )
        from project.service_layer.webhooks.webhook_mapper_context import (
            WebhookMapperContext,
        )

        img = ImageCreatedEvent(
            id=1,
            hash=99999,
            encoding_format="image/jpeg",
            copyright_text=None,
            license_id=None,
        )
        ctx = WebhookMapperContext()
        result = ImageCreated.from_event(img, ctx)
        assert result is not None


def test_image_updated_payload_from_event_with_image(app):
    with app.test_request_context("/"):
        from project.domain.events.image_updated import (
            ImageUpdated as ImageUpdatedEvent,
        )
        from project.service_layer.webhooks.payloads.nested.image_updated import (
            ImageUpdated,
        )
        from project.service_layer.webhooks.webhook_mapper_context import (
            WebhookMapperContext,
        )

        img = ImageUpdatedEvent(
            id=1,
            hash=99999,
            data_changed=True,
            encoding_format=None,
            copyright_text=None,
            license_id=None,
        )
        ctx = WebhookMapperContext()
        result = ImageUpdated.from_event(img, ctx)
        assert result is not None


def test_location_created_payload_from_event_with_location():
    from project.domain.events.location_created import (
        LocationCreated as LocationCreatedEvent,
    )
    from project.service_layer.webhooks.payloads.nested.location_created import (
        LocationCreated,
    )

    loc = LocationCreatedEvent(
        street="Main St",
        postalCode="12345",
        city="Berlin",
        state="Berlin",
        country="DE",
        latitude=52.5,
        longitude=13.4,
    )
    result = LocationCreated.from_event(loc, ctx=None)
    assert result is not None
    assert result.city == "Berlin"


def test_location_updated_payload_from_event_with_location():
    from project.domain.events.location_updated import (
        LocationUpdated as LocationUpdatedEvent,
    )
    from project.service_layer.webhooks.payloads.nested.location_updated import (
        LocationUpdated,
    )

    loc = LocationUpdatedEvent(
        street=None,
        postalCode=None,
        city=None,
        state=None,
        country=None,
        latitude=None,
        longitude=None,
    )
    result = LocationUpdated.from_event(loc, ctx=None)
    assert result is not None


# ---------------------------------------------------------------------------
# Payload return cls(...) lines for all top-level payloads
# ---------------------------------------------------------------------------


def _make_ctx(app):
    """Return a WebhookMapperContext inside test_request_context."""
    from project.service_layer.webhooks.webhook_mapper_context import (
        WebhookMapperContext,
    )

    return WebhookMapperContext()


def test_app_installation_created_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.app_installation_created import (
            AppInstallationCreated,
        )
        from project.service_layer.webhooks.payloads.app_installation_created_payload import (
            AppInstallationCreatedPayload,
        )

        e = AppInstallationCreated.model_construct(
            id=1,
            admin_unit_id=10,
            app_id=5,
            permissions=["read"],
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = AppInstallationCreatedPayload.from_event(e, _make_ctx(app))
        assert result is not None
        assert result.id == 1


def test_app_installation_permissions_updated_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.app_installation_permissions_updated import (
            AppInstallationPermissionsUpdated,
        )
        from project.service_layer.webhooks.payloads.app_installation_permissions_updated_payload import (
            AppInstallationPermissionsUpdatedPayload,
        )

        e = AppInstallationPermissionsUpdated.model_construct(
            id=1,
            admin_unit_id=10,
            app_id=5,
            permissions=["read"],
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = AppInstallationPermissionsUpdatedPayload.from_event(e, _make_ctx(app))
        assert result is not None


def test_app_uninstalled_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.app_uninstalled import AppUninstalled
        from project.service_layer.webhooks.payloads.app_uninstalled_payload import (
            AppUninstalledPayload,
        )

        e = AppUninstalled.model_construct(
            id=1,
            admin_unit_id=10,
            app_id=5,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = AppUninstalledPayload.from_event(e, _make_ctx(app))
        assert result is not None


def test_event_organizer_created_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.event_organizer_created import EventOrganizerCreated
        from project.service_layer.webhooks.payloads.event_organizer_created_payload import (
            EventOrganizerCreatedPayload,
        )

        e = EventOrganizerCreated.model_construct(
            id=1,
            admin_unit_id=10,
            name="My Org",
            url=None,
            email=None,
            phone=None,
            fax=None,
            location=None,
            logo=None,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = EventOrganizerCreatedPayload.from_event(e, _make_ctx(app))
        assert result is not None
        assert result.name == "My Org"


def test_event_organizer_deleted_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.event_organizer_deleted import EventOrganizerDeleted
        from project.service_layer.webhooks.payloads.event_organizer_deleted_payload import (
            EventOrganizerDeletedPayload,
        )

        e = EventOrganizerDeleted.model_construct(
            id=1,
            admin_unit_id=10,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = EventOrganizerDeletedPayload.from_event(e, _make_ctx(app))
        assert result is not None


def test_event_organizer_updated_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.event_organizer_updated import EventOrganizerUpdated
        from project.domain.types import unset
        from project.service_layer.webhooks.payloads.event_organizer_updated_payload import (
            EventOrganizerUpdatedPayload,
        )

        e = EventOrganizerUpdated.model_construct(
            id=1,
            admin_unit_id=10,
            name=None,
            url=None,
            email=None,
            phone=None,
            fax=None,
            location=unset,
            logo=unset,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = EventOrganizerUpdatedPayload.from_event(e, _make_ctx(app))
        assert result is not None


def test_event_place_created_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.event_place_created import EventPlaceCreated
        from project.service_layer.webhooks.payloads.event_place_created_payload import (
            EventPlaceCreatedPayload,
        )

        e = EventPlaceCreated.model_construct(
            id=1,
            admin_unit_id=10,
            name="My Place",
            url=None,
            description=None,
            location=None,
            photo=None,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = EventPlaceCreatedPayload.from_event(e, _make_ctx(app))
        assert result is not None
        assert result.name == "My Place"


def test_event_place_deleted_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.event_place_deleted import EventPlaceDeleted
        from project.service_layer.webhooks.payloads.event_place_deleted_payload import (
            EventPlaceDeletedPayload,
        )

        e = EventPlaceDeleted.model_construct(
            id=1,
            admin_unit_id=10,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = EventPlaceDeletedPayload.from_event(e, _make_ctx(app))
        assert result is not None


def test_event_place_updated_payload_from_event(app):
    with app.test_request_context("/"):
        from project.domain.events.event_place_updated import EventPlaceUpdated
        from project.domain.types import unset
        from project.service_layer.webhooks.payloads.event_place_updated_payload import (
            EventPlaceUpdatedPayload,
        )

        e = EventPlaceUpdated.model_construct(
            id=1,
            admin_unit_id=10,
            name=None,
            url=None,
            description=None,
            location=unset,
            photo=unset,
            actor=None,
            timestamp=datetime.datetime.now(datetime.timezone.utc),
        )
        result = EventPlaceUpdatedPayload.from_event(e, _make_ctx(app))
        assert result is not None


# ---------------------------------------------------------------------------
# app/view_handler.py lines 51-52 – complete_object (dead code in create/update flow)
# ---------------------------------------------------------------------------


def test_app_view_handler_complete_object(app):
    """Call AppViewHandler.complete_object directly to cover lines 51-52."""
    with app.test_request_context("/"):
        from unittest.mock import MagicMock, patch

        from flask import g

        from project.views.manage_admin_unit.app.view_handler import AppViewHandler

        # Set up g.manage_admin_unit so the parent class doesn't fail
        admin_unit = MagicMock()
        admin_unit.id = 1
        g.manage_admin_unit = admin_unit

        handler = AppViewHandler()
        obj = MagicMock()
        obj.admin_unit_id = 1
        form = MagicMock()

        with patch(
            "project.views.manage_admin_unit.app.view_handler.complete_oauth2_client"
        ) as mock_complete:
            # Patch ManageAdminUnitChildViewHandler.complete_object to skip the chain
            with patch.object(
                type(handler).__mro__[1], "complete_object", return_value=None
            ):
                handler.complete_object(obj, form)

        mock_complete.assert_called_once_with(obj)


def test_webhook_delivery_child_view_handler_complete_object(app):
    """Call WebhookDeliveryChildViewHandler.complete_object to cover lines 28-29."""
    with app.test_request_context("/"):
        from unittest.mock import MagicMock, patch

        from flask import g

        from project.views.manage_admin_unit.app.webhook_delivery.view_handler import (
            handler as delivery_view_handler,
        )
        from project.views.manage_admin_unit.app.webhook_delivery.webhook_delivery_attempt.view_handler import (
            WebhookDeliveryAttemptViewHandler,
        )

        admin_unit = MagicMock()
        admin_unit.id = 1
        g.manage_admin_unit = admin_unit

        current_app_mock = MagicMock()
        current_app_mock.id = 10
        g.current_app = current_app_mock

        current_delivery_mock = MagicMock()
        current_delivery_mock.id = 20
        g.current_webhook_delivery = current_delivery_mock

        handler = WebhookDeliveryAttemptViewHandler(parent=delivery_view_handler)
        obj = MagicMock()
        form = MagicMock()

        # Patch ManageAdminUnitChildViewHandler.complete_object (MRO[3]) to skip the chain
        with patch.object(
            type(handler).__mro__[3], "complete_object", return_value=None
        ):
            handler.complete_object(obj, form)

        # WebhookDeliveryChildViewHandler.complete_object sets webhook_delivery_id
        assert obj.webhook_delivery_id == 20
