"""empty message

Revision ID: 00f2c5b629f3
Revises: 6b8e1f2e6676
Create Date: 2025-09-06 13:47:31.191137

"""

import flask_security
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "00f2c5b629f3"
down_revision = "6b8e1f2e6676"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_installation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_unit_id", sa.Integer(), nullable=True),
        sa.Column("oauth2_client_id", sa.Integer(), nullable=True),
        sa.Column("permissions", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["adminunit.id"],
            name=op.f("fk_app_installation_admin_unit_id_adminunit"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name=op.f("fk_app_installation_created_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["oauth2_client_id"],
            ["oauth2_client.id"],
            name=op.f("fk_app_installation_oauth2_client_id_oauth2_client"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
            name=op.f("fk_app_installation_updated_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_installation")),
        sa.UniqueConstraint(
            "admin_unit_id",
            "oauth2_client_id",
            name=op.f("uq_app_installation_admin_unit_id"),
        ),
    )
    op.create_table(
        "app_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_unit_id", sa.Integer(), nullable=False),
        sa.Column("oauth2_client_id", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=255), nullable=False),
        sa.Column("kid", sa.Unicode(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["adminunit.id"],
            name=op.f("fk_app_key_admin_unit_id_adminunit"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name=op.f("fk_app_key_created_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["oauth2_client_id"],
            ["oauth2_client.id"],
            name=op.f("fk_app_key_oauth2_client_id_oauth2_client"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
            name=op.f("fk_app_key_updated_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_key")),
        sa.UniqueConstraint("kid", "oauth2_client_id", name=op.f("uq_app_key_kid")),
    )
    op.create_index(op.f("ix_app_key_kid"), "app_key", ["kid"], unique=False)
    op.add_column(
        "oauth2_client", sa.Column("admin_unit_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "oauth2_client",
        sa.Column("app_permissions", flask_security.datastore.AsaList(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_admin_unit_id_adminunit"),
        "oauth2_client",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("oauth2_token", sa.Column("app_id", sa.Integer(), nullable=True))
    op.add_column(
        "oauth2_token", sa.Column("app_installation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_oauth2_token_app_id_oauth2_client"),
        "oauth2_token",
        "oauth2_client",
        ["app_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_token_app_installation_id_app_installation"),
        "oauth2_token",
        "app_installation",
        ["app_installation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    op.alter_column("oauth2_client", "user_id", nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_oauth2_token_app_installation_id_app_installation"),
        "oauth2_token",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_oauth2_token_app_id_oauth2_client"), "oauth2_token", type_="foreignkey"
    )
    op.drop_column("oauth2_token", "app_installation_id")
    op.drop_column("oauth2_token", "app_id")
    op.drop_constraint(
        op.f("fk_oauth2_client_admin_unit_id_adminunit"),
        "oauth2_client",
        type_="foreignkey",
    )
    op.drop_column("oauth2_client", "app_permissions")
    op.drop_column("oauth2_client", "admin_unit_id")
    op.drop_index(op.f("ix_app_key_kid"), table_name="app_key")
    op.drop_table("app_key")
    op.drop_table("app_installation")
    # ### end Alembic commands ###
