"""empty message

Revision ID: 0e8b84009307
Revises: b13285e0d85f
Create Date: 2025-10-12 07:19:17.104196

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "0e8b84009307"
down_revision = "b13285e0d85f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth2_client", sa.Column("homepage_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("setup_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("webhook_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "oauth2_client",
        sa.Column("webhook_secret", sa.Unicode(length=255), nullable=True),
    )
    op.add_column(
        "oauth2_client", sa.Column("description", sa.UnicodeText(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_client", "description")
    op.drop_column("oauth2_client", "webhook_secret")
    op.drop_column("oauth2_client", "webhook_url")
    op.drop_column("oauth2_client", "setup_url")
    op.drop_column("oauth2_client", "homepage_url")
    # ### end Alembic commands ###
