"""empty message

Revision ID: 1615a65076d4
Revises: a996bd014013
Create Date: 2025-04-12 15:46:36.236517

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "1615a65076d4"
down_revision = "a996bd014013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("internal_tags", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "internal_tags")
    # ### end Alembic commands ###
