"""empty message

Revision ID: 19f60369961e
Revises: ef547963d7f0
Create Date: 2024-12-11 15:57:03.203179

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "19f60369961e"
down_revision = "ef547963d7f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("adminunit", "suggestions_enabled")
    op.drop_table("eventsuggestion_eventcategories")
    op.drop_table("eventsuggestion")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adminunit",
        sa.Column(
            "suggestions_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
