"""empty message

Revision ID: 2fad15d1815e
Revises: 6f7e83acf944
Create Date: 2026-03-27 20:28:19.638813

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "2fad15d1815e"
down_revision = "6f7e83acf944"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Unicode(length=255), nullable=True),
        sa.Column("secret", sa.Unicode(length=255), nullable=True),
        sa.Column("disabled", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "event_types",
            postgresql.ARRAY(sa.Unicode(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook")),
    )
    op.create_index(
        "idx_webhook_event_types",
        "webhook",
        ["event_types"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "webhook_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.Unicode(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_event")),
    )
    op.create_table(
        "webhook_delivery",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webhook_event_id", sa.Integer(), nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("app_installation_id", sa.Integer(), nullable=True),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["oauth2_client.id"],
            name=op.f("fk_webhook_delivery_app_id_oauth2_client"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["app_installation_id"],
            ["app_installation.id"],
            name=op.f("fk_webhook_delivery_app_installation_id_app_installation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"],
            ["webhook_event.id"],
            name=op.f("fk_webhook_delivery_webhook_event_id_webhook_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhook.id"],
            name=op.f("fk_webhook_delivery_webhook_id_webhook"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_delivery")),
    )
    op.create_table(
        "webhook_delivery_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Unicode(length=255), nullable=False),
        sa.Column("status", sa.Unicode(length=255), nullable=True),
        sa.Column("status_code", sa.Unicode(length=255), nullable=True),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("webhook_delivery_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["webhook_delivery_id"],
            ["webhook_delivery.id"],
            name=op.f(
                "fk_webhook_delivery_attempt_webhook_delivery_id_webhook_delivery"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_delivery_attempt")),
    )
    op.add_column("oauth2_client", sa.Column("webhook_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_oauth2_client_webhook_id_webhook"),
        "oauth2_client",
        "webhook",
        ["webhook_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("oauth2_client", "webhook_url")
    op.drop_column("oauth2_client", "webhook_secret")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth2_client",
        sa.Column(
            "webhook_secret", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "oauth2_client",
        sa.Column(
            "webhook_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_webhook_id_webhook"), "oauth2_client", type_="foreignkey"
    )
    op.drop_column("oauth2_client", "webhook_id")
    op.drop_table("webhook_delivery_attempt")
    op.drop_table("webhook_delivery")
    op.drop_table("webhook_event")
    op.drop_index(
        "idx_webhook_event_types", table_name="webhook", postgresql_using="gin"
    )
    op.drop_table("webhook")
    # ### end Alembic commands ###
