"""empty message

Revision ID: 31b60d93351d
Revises: 3c5b34fd1156
Create Date: 2020-12-12 13:48:34.244288

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "31b60d93351d"
down_revision = "3c5b34fd1156"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tos", sa.UnicodeText(), nullable=True),
        sa.Column("legal_notice", sa.UnicodeText(), nullable=True),
        sa.Column("contact", sa.UnicodeText(), nullable=True),
        sa.Column("privacy", sa.UnicodeText(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("settings")
    # ### end Alembic commands ###
