"""empty message

Revision ID: 36945eb387b4
Revises: 0533e4f24f00
Create Date: 2020-06-06 18:59:17.649176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36945eb387b4'
down_revision = '0533e4f24f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###
