"""empty message

Revision ID: 39c10788ec62
Revises: 00f2c5b629f3
Create Date: 2025-09-06 15:16:31.322795

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "39c10788ec62"
down_revision = "00f2c5b629f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adminunit",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunit",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_adminunit_created_by_app_installation_id_app_installation"),
        "adminunit",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunit_updated_by_app_installation_id_app_installation"),
        "adminunit",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "adminunitinvitation",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunitinvitation",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_adminunitinvitation_created_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunitinvitation_updated_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "adminunitrelation",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunitrelation",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_adminunitrelation_created_by_app_installation_id_app_installation"),
        "adminunitrelation",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunitrelation_updated_by_app_installation_id_app_installation"),
        "adminunitrelation",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "adminunitverificationrequest",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunitverificationrequest",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f(
            "fk_adminunitverificationrequest_created_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f(
            "fk_adminunitverificationrequest_updated_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "apikey",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "apikey",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_apikey_updated_by_app_installation_id_app_installation"),
        "apikey",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_apikey_created_by_app_installation_id_app_installation"),
        "apikey",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "app_installation",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "app_installation",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_app_installation_created_by_app_installation_id_app_installation"),
        "app_installation",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_app_installation_updated_by_app_installation_id_app_installation"),
        "app_installation",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "app_key",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "app_key",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_app_key_updated_by_app_installation_id_app_installation"),
        "app_key",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_app_key_created_by_app_installation_id_app_installation"),
        "app_key",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "customwidget",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "customwidget",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_customwidget_created_by_app_installation_id_app_installation"),
        "customwidget",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_customwidget_updated_by_app_installation_id_app_installation"),
        "customwidget",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "event",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "event",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_event_updated_by_app_installation_id_app_installation"),
        "event",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_event_created_by_app_installation_id_app_installation"),
        "event",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventlist",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventlist",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventlist_created_by_app_installation_id_app_installation"),
        "eventlist",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventlist_updated_by_app_installation_id_app_installation"),
        "eventlist",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventorganizer",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventorganizer",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_created_by_app_installation_id_app_installation"),
        "eventorganizer",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_updated_by_app_installation_id_app_installation"),
        "eventorganizer",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventplace",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventplace",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventplace_updated_by_app_installation_id_app_installation"),
        "eventplace",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventplace_created_by_app_installation_id_app_installation"),
        "eventplace",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventreference",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventreference",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventreference_updated_by_app_installation_id_app_installation"),
        "eventreference",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventreference_created_by_app_installation_id_app_installation"),
        "eventreference",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventreferencerequest",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventreferencerequest",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f(
            "fk_eventreferencerequest_created_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f(
            "fk_eventreferencerequest_updated_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "image",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "image",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_image_updated_by_app_installation_id_app_installation"),
        "image",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_image_created_by_app_installation_id_app_installation"),
        "image",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "license",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "license",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_license_updated_by_app_installation_id_app_installation"),
        "license",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_license_created_by_app_installation_id_app_installation"),
        "license",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "location",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "location",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_location_updated_by_app_installation_id_app_installation"),
        "location",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_location_created_by_app_installation_id_app_installation"),
        "location",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "settings",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "settings",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_settings_updated_by_app_installation_id_app_installation"),
        "settings",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_settings_created_by_app_installation_id_app_installation"),
        "settings",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_settings_created_by_app_installation_id_app_installation"),
        "settings",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_settings_updated_by_app_installation_id_app_installation"),
        "settings",
        type_="foreignkey",
    )
    op.drop_column("settings", "updated_by_app_installation_id")
    op.drop_column("settings", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_location_created_by_app_installation_id_app_installation"),
        "location",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_location_updated_by_app_installation_id_app_installation"),
        "location",
        type_="foreignkey",
    )
    op.drop_column("location", "updated_by_app_installation_id")
    op.drop_column("location", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_license_created_by_app_installation_id_app_installation"),
        "license",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_license_updated_by_app_installation_id_app_installation"),
        "license",
        type_="foreignkey",
    )
    op.drop_column("license", "updated_by_app_installation_id")
    op.drop_column("license", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_image_created_by_app_installation_id_app_installation"),
        "image",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_image_updated_by_app_installation_id_app_installation"),
        "image",
        type_="foreignkey",
    )
    op.drop_column("image", "updated_by_app_installation_id")
    op.drop_column("image", "created_by_app_installation_id")
    op.drop_constraint(
        op.f(
            "fk_eventreferencerequest_updated_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_eventreferencerequest_created_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.drop_column("eventreferencerequest", "updated_by_app_installation_id")
    op.drop_column("eventreferencerequest", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventreference_created_by_app_installation_id_app_installation"),
        "eventreference",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventreference_updated_by_app_installation_id_app_installation"),
        "eventreference",
        type_="foreignkey",
    )
    op.drop_column("eventreference", "updated_by_app_installation_id")
    op.drop_column("eventreference", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventplace_created_by_app_installation_id_app_installation"),
        "eventplace",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventplace_updated_by_app_installation_id_app_installation"),
        "eventplace",
        type_="foreignkey",
    )
    op.drop_column("eventplace", "updated_by_app_installation_id")
    op.drop_column("eventplace", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventorganizer_updated_by_app_installation_id_app_installation"),
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventorganizer_created_by_app_installation_id_app_installation"),
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_column("eventorganizer", "updated_by_app_installation_id")
    op.drop_column("eventorganizer", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventlist_updated_by_app_installation_id_app_installation"),
        "eventlist",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventlist_created_by_app_installation_id_app_installation"),
        "eventlist",
        type_="foreignkey",
    )
    op.drop_column("eventlist", "updated_by_app_installation_id")
    op.drop_column("eventlist", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_event_created_by_app_installation_id_app_installation"),
        "event",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_updated_by_app_installation_id_app_installation"),
        "event",
        type_="foreignkey",
    )
    op.drop_column("event", "updated_by_app_installation_id")
    op.drop_column("event", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_customwidget_updated_by_app_installation_id_app_installation"),
        "customwidget",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_customwidget_created_by_app_installation_id_app_installation"),
        "customwidget",
        type_="foreignkey",
    )
    op.drop_column("customwidget", "updated_by_app_installation_id")
    op.drop_column("customwidget", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_app_key_created_by_app_installation_id_app_installation"),
        "app_key",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_app_key_updated_by_app_installation_id_app_installation"),
        "app_key",
        type_="foreignkey",
    )
    op.drop_column("app_key", "updated_by_app_installation_id")
    op.drop_column("app_key", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_app_installation_updated_by_app_installation_id_app_installation"),
        "app_installation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_app_installation_created_by_app_installation_id_app_installation"),
        "app_installation",
        type_="foreignkey",
    )
    op.drop_column("app_installation", "updated_by_app_installation_id")
    op.drop_column("app_installation", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_apikey_created_by_app_installation_id_app_installation"),
        "apikey",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_apikey_updated_by_app_installation_id_app_installation"),
        "apikey",
        type_="foreignkey",
    )
    op.drop_column("apikey", "updated_by_app_installation_id")
    op.drop_column("apikey", "created_by_app_installation_id")
    op.drop_constraint(
        op.f(
            "fk_adminunitverificationrequest_updated_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_adminunitverificationrequest_created_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        type_="foreignkey",
    )
    op.drop_column("adminunitverificationrequest", "updated_by_app_installation_id")
    op.drop_column("adminunitverificationrequest", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_adminunitrelation_updated_by_app_installation_id_app_installation"),
        "adminunitrelation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunitrelation_created_by_app_installation_id_app_installation"),
        "adminunitrelation",
        type_="foreignkey",
    )
    op.drop_column("adminunitrelation", "updated_by_app_installation_id")
    op.drop_column("adminunitrelation", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_adminunitinvitation_updated_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunitinvitation_created_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        type_="foreignkey",
    )
    op.drop_column("adminunitinvitation", "updated_by_app_installation_id")
    op.drop_column("adminunitinvitation", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_adminunit_updated_by_app_installation_id_app_installation"),
        "adminunit",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunit_created_by_app_installation_id_app_installation"),
        "adminunit",
        type_="foreignkey",
    )
    op.drop_column("adminunit", "updated_by_app_installation_id")
    op.drop_column("adminunit", "created_by_app_installation_id")
    # ### end Alembic commands ###
