"""empty message

Revision ID: 6b8e1f2e6676
Revises: 875f2799acd8
Create Date: 2025-07-13 14:46:05.737542

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "6b8e1f2e6676"
down_revision = "875f2799acd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customeventcategoryset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=255), nullable=False),
        sa.Column("label", sa.Unicode(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customeventcategoryset")),
    )
    op.create_table(
        "customeventcategory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=255), nullable=False),
        sa.Column("label", sa.Unicode(length=255), nullable=True),
        sa.Column("category_set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_set_id"],
            ["customeventcategoryset.id"],
            name=op.f("fk_customeventcategory_category_set_id_customeventcategoryset"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customeventcategory")),
        sa.UniqueConstraint(
            "name", "category_set_id", name=op.f("uq_customeventcategory_name")
        ),
    )
    op.create_table(
        "event_customeventcategories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["customeventcategory.id"],
            name=op.f("fk_event_customeventcategories_category_id_customeventcategory"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
            name=op.f("fk_event_customeventcategories_event_id_event"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_customeventcategories")),
        sa.UniqueConstraint(
            "event_id",
            "category_id",
            name=op.f("uq_event_customeventcategories_event_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_customeventcategories")
    op.drop_table("customeventcategory")
    op.drop_table("customeventcategoryset")
    # ### end Alembic commands ###
