"""empty message

Revision ID: 6f7e83acf944
Revises: 74c5e8dae8ab
Create Date: 2025-12-12 19:30:50.478601

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "6f7e83acf944"
down_revision = "74c5e8dae8ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "adminunitmemberroles_members",
        "member_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "adminunitmemberroles_members",
        "role_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_adminunitmemberroles_members_member_id"),
        "adminunitmemberroles_members",
        ["member_id", "role_id"],
    )
    op.drop_constraint(
        "fk_adminunitmemberroles_members_member_id_adminunitmember",
        "adminunitmemberroles_members",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_adminunitmemberroles_members_role_id_adminunitmemberrole",
        "adminunitmemberroles_members",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_adminunitmemberroles_members_role_id_adminunitmemberrole"),
        "adminunitmemberroles_members",
        "adminunitmemberrole",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_adminunitmemberroles_members_member_id_adminunitmember"),
        "adminunitmemberroles_members",
        "adminunitmember",
        ["member_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_event_coorganizers_organizer_id_eventorganizer",
        "event_coorganizers",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_event_coorganizers_event_id_event", "event_coorganizers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_event_coorganizers_event_id_event"),
        "event_coorganizers",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_event_coorganizers_organizer_id_eventorganizer"),
        "event_coorganizers",
        "eventorganizer",
        ["organizer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_event_customeventcategories_event_id",
        "event_customeventcategories",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_event_customeventcategories_category_id"),
        "event_customeventcategories",
        ["category_id", "event_id"],
    )
    op.drop_constraint(
        "fk_event_customeventcategories_event_id_event",
        "event_customeventcategories",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_event_customeventcategories_category_id_customeventcategory",
        "event_customeventcategories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_event_customeventcategories_event_id_event"),
        "event_customeventcategories",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_event_customeventcategories_category_id_customeventcategory"),
        "event_customeventcategories",
        "customeventcategory",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_event_eventcategories_event_id", "event_eventcategories", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_event_eventcategories_category_id"),
        "event_eventcategories",
        ["category_id", "event_id"],
    )
    op.drop_constraint(
        "fk_event_eventcategories_category_id_eventcategory",
        "event_eventcategories",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_event_eventcategories_event_id_event",
        "event_eventcategories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_event_eventcategories_event_id_event"),
        "event_eventcategories",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_event_eventcategories_category_id_eventcategory"),
        "event_eventcategories",
        "eventcategory",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_event_eventlists_event_id", "event_eventlists", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_event_eventlists_list_id"), "event_eventlists", ["list_id", "event_id"]
    )
    op.drop_constraint(
        "fk_event_eventlists_list_id_eventlist", "event_eventlists", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_event_eventlists_event_id_event", "event_eventlists", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_event_eventlists_event_id_event"),
        "event_eventlists",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_event_eventlists_list_id_eventlist"),
        "event_eventlists",
        "eventlist",
        ["list_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "roles_users", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "roles_users", "role_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_unique_constraint(
        op.f("uq_roles_users_user_id"), "roles_users", ["user_id", "role_id"]
    )
    op.drop_constraint("fk_roles_users_role_id_role", "roles_users", type_="foreignkey")
    op.drop_constraint("fk_roles_users_user_id_user", "roles_users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_roles_users_role_id_role"),
        "roles_users",
        "role",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_roles_users_user_id_user"),
        "roles_users",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_user_favoriteevents_event_id_event",
        "user_favoriteevents",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_user_favoriteevents_user_id_user", "user_favoriteevents", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_user_favoriteevents_event_id_event"),
        "user_favoriteevents",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_favoriteevents_user_id_user"),
        "user_favoriteevents",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_favoriteevents_user_id_user"),
        "user_favoriteevents",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_favoriteevents_event_id_event"),
        "user_favoriteevents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_favoriteevents_user_id_user",
        "user_favoriteevents",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_user_favoriteevents_event_id_event",
        "user_favoriteevents",
        "event",
        ["event_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_roles_users_user_id_user"), "roles_users", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_roles_users_role_id_role"), "roles_users", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_roles_users_user_id_user", "roles_users", "user", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_roles_users_role_id_role", "roles_users", "role", ["role_id"], ["id"]
    )
    op.drop_constraint(op.f("uq_roles_users_user_id"), "roles_users", type_="unique")
    op.alter_column("roles_users", "role_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("roles_users", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(
        op.f("fk_event_eventlists_list_id_eventlist"),
        "event_eventlists",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_eventlists_event_id_event"),
        "event_eventlists",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_event_eventlists_event_id_event",
        "event_eventlists",
        "event",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_event_eventlists_list_id_eventlist",
        "event_eventlists",
        "eventlist",
        ["list_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_event_eventlists_list_id"), "event_eventlists", type_="unique"
    )
    op.create_unique_constraint(
        "uq_event_eventlists_event_id", "event_eventlists", ["event_id", "list_id"]
    )
    op.drop_constraint(
        op.f("fk_event_eventcategories_category_id_eventcategory"),
        "event_eventcategories",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_eventcategories_event_id_event"),
        "event_eventcategories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_event_eventcategories_event_id_event",
        "event_eventcategories",
        "event",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_event_eventcategories_category_id_eventcategory",
        "event_eventcategories",
        "eventcategory",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_event_eventcategories_category_id"),
        "event_eventcategories",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_event_eventcategories_event_id",
        "event_eventcategories",
        ["event_id", "category_id"],
    )
    op.drop_constraint(
        op.f("fk_event_customeventcategories_category_id_customeventcategory"),
        "event_customeventcategories",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_customeventcategories_event_id_event"),
        "event_customeventcategories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_event_customeventcategories_category_id_customeventcategory",
        "event_customeventcategories",
        "customeventcategory",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_event_customeventcategories_event_id_event",
        "event_customeventcategories",
        "event",
        ["event_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_event_customeventcategories_category_id"),
        "event_customeventcategories",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_event_customeventcategories_event_id",
        "event_customeventcategories",
        ["event_id", "category_id"],
    )
    op.drop_constraint(
        op.f("fk_event_coorganizers_organizer_id_eventorganizer"),
        "event_coorganizers",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_coorganizers_event_id_event"),
        "event_coorganizers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_event_coorganizers_event_id_event",
        "event_coorganizers",
        "event",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_event_coorganizers_organizer_id_eventorganizer",
        "event_coorganizers",
        "eventorganizer",
        ["organizer_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_adminunitmemberroles_members_member_id_adminunitmember"),
        "adminunitmemberroles_members",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunitmemberroles_members_role_id_adminunitmemberrole"),
        "adminunitmemberroles_members",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_adminunitmemberroles_members_role_id_adminunitmemberrole",
        "adminunitmemberroles_members",
        "adminunitmemberrole",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_adminunitmemberroles_members_member_id_adminunitmember",
        "adminunitmemberroles_members",
        "adminunitmember",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_adminunitmemberroles_members_member_id"),
        "adminunitmemberroles_members",
        type_="unique",
    )
    op.alter_column(
        "adminunitmemberroles_members",
        "role_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "adminunitmemberroles_members",
        "member_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
