"""empty message

Revision ID: 74c5e8dae8ab
Revises: 0e8b84009307
Create Date: 2025-12-08 17:46:35.552316

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "74c5e8dae8ab"
down_revision = "0e8b84009307"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_adminunit_logo_id_image", "adminunit", type_="foreignkey")
    op.drop_constraint(
        "fk_adminunit_deletion_requested_by_id_user", "adminunit", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_adminunit_location_id_location", "adminunit", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_adminunit_logo_id_image"),
        "adminunit",
        "image",
        ["logo_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunit_deletion_requested_by_id_user"),
        "adminunit",
        "user",
        ["deletion_requested_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunit_location_id_location"),
        "adminunit",
        "location",
        ["location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "fk_adminunitinvitation_admin_unit_id_adminunit",
        "adminunitinvitation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_adminunitinvitation_admin_unit_id_adminunit"),
        "adminunitinvitation",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_adminunitmember_admin_unit_id_adminunit",
        "adminunitmember",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_adminunitmember_admin_unit_id_adminunit"),
        "adminunitmember",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_adminunitmemberinvitation_admin_unit_id_adminunit",
        "adminunitmemberinvitation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_adminunitmemberinvitation_admin_unit_id_adminunit"),
        "adminunitmemberinvitation",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "apikey",
        sa.Column("max_api_keys", sa.Integer(), server_default="1", nullable=False),
    )
    op.alter_column(
        "app_installation", "admin_unit_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "app_installation",
        "oauth2_client_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "fk_customwidget_admin_unit_id_adminunit", "customwidget", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_customwidget_admin_unit_id_adminunit"),
        "customwidget",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_event_photo_id_image", "event", type_="foreignkey")
    op.drop_constraint("fk_event_admin_unit_id_adminunit", "event", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_event_admin_unit_id_adminunit"),
        "event",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_event_photo_id_image"),
        "event",
        "image",
        ["photo_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("fk_eventdate_event_id_event", "eventdate", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_eventdate_event_id_event"),
        "eventdate",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_eventdatedefinition_event_id_event",
        "eventdatedefinition",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_eventdatedefinition_event_id_event"),
        "eventdatedefinition",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_eventlist_admin_unit_id_adminunit", "eventlist", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_eventlist_admin_unit_id_adminunit"),
        "eventlist",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "eventorganizer", "admin_unit_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        "fk_eventorganizer_admin_unit_id_adminunit",
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_eventorganizer_logo_id_image", "eventorganizer", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_eventorganizer_location_id_location", "eventorganizer", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_logo_id_image"),
        "eventorganizer",
        "image",
        ["logo_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_admin_unit_id_adminunit"),
        "eventorganizer",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_location_id_location"),
        "eventorganizer",
        "location",
        ["location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "eventplace", "admin_unit_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        "fk_eventplace_location_id_location", "eventplace", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_eventplace_admin_unit_id_adminunit", "eventplace", type_="foreignkey"
    )
    op.drop_constraint("fk_eventplace_photo_id_image", "eventplace", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_eventplace_admin_unit_id_adminunit"),
        "eventplace",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_eventplace_photo_id_image"),
        "eventplace",
        "image",
        ["photo_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventplace_location_id_location"),
        "eventplace",
        "location",
        ["location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "fk_eventreference_admin_unit_id_adminunit",
        "eventreference",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_eventreference_event_id_event", "eventreference", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_eventreference_admin_unit_id_adminunit"),
        "eventreference",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_eventreference_event_id_event"),
        "eventreference",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_eventreferencerequest_event_id_event",
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_eventreferencerequest_admin_unit_id_adminunit",
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_eventreferencerequest_event_id_event"),
        "eventreferencerequest",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_eventreferencerequest_admin_unit_id_adminunit"),
        "eventreferencerequest",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_image_license_id_license", "image", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_image_license_id_license"),
        "image",
        "license",
        ["license_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "oauth2_code", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("oauth2_code", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("fk_image_license_id_license"), "image", type_="foreignkey")
    op.create_foreign_key(
        "fk_image_license_id_license", "image", "license", ["license_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_eventreferencerequest_admin_unit_id_adminunit"),
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventreferencerequest_event_id_event"),
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_eventreferencerequest_admin_unit_id_adminunit",
        "eventreferencerequest",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_eventreferencerequest_event_id_event",
        "eventreferencerequest",
        "event",
        ["event_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_eventreference_event_id_event"), "eventreference", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_eventreference_admin_unit_id_adminunit"),
        "eventreference",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_eventreference_event_id_event",
        "eventreference",
        "event",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_eventreference_admin_unit_id_adminunit",
        "eventreference",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_eventplace_location_id_location"), "eventplace", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_eventplace_photo_id_image"), "eventplace", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_eventplace_admin_unit_id_adminunit"), "eventplace", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_eventplace_photo_id_image", "eventplace", "image", ["photo_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_eventplace_admin_unit_id_adminunit",
        "eventplace",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_eventplace_location_id_location",
        "eventplace",
        "location",
        ["location_id"],
        ["id"],
    )
    op.alter_column(
        "eventplace", "admin_unit_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_eventorganizer_location_id_location"),
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventorganizer_admin_unit_id_adminunit"),
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventorganizer_logo_id_image"), "eventorganizer", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_eventorganizer_location_id_location",
        "eventorganizer",
        "location",
        ["location_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_eventorganizer_logo_id_image",
        "eventorganizer",
        "image",
        ["logo_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_eventorganizer_admin_unit_id_adminunit",
        "eventorganizer",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.alter_column(
        "eventorganizer", "admin_unit_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_eventlist_admin_unit_id_adminunit"), "eventlist", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_eventlist_admin_unit_id_adminunit",
        "eventlist",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_eventdatedefinition_event_id_event"),
        "eventdatedefinition",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_eventdatedefinition_event_id_event",
        "eventdatedefinition",
        "event",
        ["event_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_eventdate_event_id_event"), "eventdate", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_eventdate_event_id_event", "eventdate", "event", ["event_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_event_photo_id_image"), "event", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_event_admin_unit_id_adminunit"), "event", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_event_admin_unit_id_adminunit",
        "event",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_event_photo_id_image", "event", "image", ["photo_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_customwidget_admin_unit_id_adminunit"),
        "customwidget",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_customwidget_admin_unit_id_adminunit",
        "customwidget",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.alter_column(
        "app_installation",
        "oauth2_client_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "app_installation", "admin_unit_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("apikey", "max_api_keys")
    op.drop_constraint(
        op.f("fk_adminunitmemberinvitation_admin_unit_id_adminunit"),
        "adminunitmemberinvitation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_adminunitmemberinvitation_admin_unit_id_adminunit",
        "adminunitmemberinvitation",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_adminunitmember_admin_unit_id_adminunit"),
        "adminunitmember",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_adminunitmember_admin_unit_id_adminunit",
        "adminunitmember",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_adminunitinvitation_admin_unit_id_adminunit"),
        "adminunitinvitation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_adminunitinvitation_admin_unit_id_adminunit",
        "adminunitinvitation",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_adminunit_location_id_location"), "adminunit", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_adminunit_deletion_requested_by_id_user"),
        "adminunit",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunit_logo_id_image"), "adminunit", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_adminunit_location_id_location",
        "adminunit",
        "location",
        ["location_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_adminunit_deletion_requested_by_id_user",
        "adminunit",
        "user",
        ["deletion_requested_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_adminunit_logo_id_image", "adminunit", "image", ["logo_id"], ["id"]
    )
    # ### end Alembic commands ###
