"""empty message

Revision ID: a626456fc25e
Revises: 84d692aa450c
Create Date: 2025-05-13 14:10:29.980879

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "a626456fc25e"
down_revision = "84d692aa450c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adminunit",
        sa.Column("max_api_keys", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("max_api_keys", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "max_api_keys")
    op.drop_column("adminunit", "max_api_keys")
    # ### end Alembic commands ###
