"""empty message

Revision ID: a8c662c46047
Revises: 8f4df40a36f3
Create Date: 2020-09-25 11:26:03.139800

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import dbtypes


# revision identifiers, used by Alembic.
revision = 'a8c662c46047'
down_revision = '8f4df40a36f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminunitmemberrole', sa.Column('title', sa.Unicode(length=255), nullable=True))
    op.add_column('role', sa.Column('title', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'title')
    op.drop_column('adminunitmemberrole', 'title')
    # ### end Alembic commands ###
