"""empty message

Revision ID: b13285e0d85f
Revises: 6b8e1f2e6676
Create Date: 2025-09-11 12:04:10.191694

"""

import flask_security
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "b13285e0d85f"
down_revision = "6b8e1f2e6676"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_installation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_unit_id", sa.Integer(), nullable=True),
        sa.Column("oauth2_client_id", sa.Integer(), nullable=True),
        sa.Column("permissions", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["adminunit.id"],
            name=op.f("fk_app_installation_admin_unit_id_adminunit"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_app_installation_id"],
            ["app_installation.id"],
            name=op.f(
                "fk_app_installation_created_by_app_installation_id_app_installation"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name=op.f("fk_app_installation_created_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["oauth2_client_id"],
            ["oauth2_client.id"],
            name=op.f("fk_app_installation_oauth2_client_id_oauth2_client"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_app_installation_id"],
            ["app_installation.id"],
            name=op.f(
                "fk_app_installation_updated_by_app_installation_id_app_installation"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
            name=op.f("fk_app_installation_updated_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_installation")),
        sa.UniqueConstraint(
            "admin_unit_id",
            "oauth2_client_id",
            name=op.f("uq_app_installation_admin_unit_id"),
        ),
    )
    op.create_table(
        "app_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_unit_id", sa.Integer(), nullable=False),
        sa.Column("oauth2_client_id", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=255), nullable=False),
        sa.Column("kid", sa.Unicode(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["adminunit.id"],
            name=op.f("fk_app_key_admin_unit_id_adminunit"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_app_installation_id"],
            ["app_installation.id"],
            name=op.f("fk_app_key_created_by_app_installation_id_app_installation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name=op.f("fk_app_key_created_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["oauth2_client_id"],
            ["oauth2_client.id"],
            name=op.f("fk_app_key_oauth2_client_id_oauth2_client"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_app_installation_id"],
            ["app_installation.id"],
            name=op.f("fk_app_key_updated_by_app_installation_id_app_installation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
            name=op.f("fk_app_key_updated_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_key")),
        sa.UniqueConstraint("kid", "oauth2_client_id", name=op.f("uq_app_key_kid")),
    )
    op.create_index(op.f("ix_app_key_kid"), "app_key", ["kid"], unique=False)
    op.add_column(
        "adminunit",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunit",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_adminunit_updated_by_app_installation_id_app_installation"),
        "adminunit",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunit_created_by_app_installation_id_app_installation"),
        "adminunit",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "adminunitinvitation",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunitinvitation",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_adminunitinvitation_created_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunitinvitation_updated_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "adminunitrelation",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunitrelation",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_adminunitrelation_updated_by_app_installation_id_app_installation"),
        "adminunitrelation",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_adminunitrelation_created_by_app_installation_id_app_installation"),
        "adminunitrelation",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "adminunitverificationrequest",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "adminunitverificationrequest",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f(
            "fk_adminunitverificationrequest_updated_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f(
            "fk_adminunitverificationrequest_created_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "apikey",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "apikey",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_apikey_updated_by_app_installation_id_app_installation"),
        "apikey",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_apikey_created_by_app_installation_id_app_installation"),
        "apikey",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "customwidget",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "customwidget",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_customwidget_updated_by_app_installation_id_app_installation"),
        "customwidget",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_customwidget_created_by_app_installation_id_app_installation"),
        "customwidget",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "event",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "event",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_event_created_by_app_installation_id_app_installation"),
        "event",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_event_updated_by_app_installation_id_app_installation"),
        "event",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventlist",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventlist",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventlist_updated_by_app_installation_id_app_installation"),
        "eventlist",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventlist_created_by_app_installation_id_app_installation"),
        "eventlist",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventorganizer",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventorganizer",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_created_by_app_installation_id_app_installation"),
        "eventorganizer",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventorganizer_updated_by_app_installation_id_app_installation"),
        "eventorganizer",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventplace",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventplace",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventplace_created_by_app_installation_id_app_installation"),
        "eventplace",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventplace_updated_by_app_installation_id_app_installation"),
        "eventplace",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventreference",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventreference",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_eventreference_created_by_app_installation_id_app_installation"),
        "eventreference",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_eventreference_updated_by_app_installation_id_app_installation"),
        "eventreference",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "eventreferencerequest",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "eventreferencerequest",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f(
            "fk_eventreferencerequest_updated_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f(
            "fk_eventreferencerequest_created_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "image",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "image",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_image_updated_by_app_installation_id_app_installation"),
        "image",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_image_created_by_app_installation_id_app_installation"),
        "image",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "license",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "license",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_license_updated_by_app_installation_id_app_installation"),
        "license",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_license_created_by_app_installation_id_app_installation"),
        "license",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "location",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "location",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_location_updated_by_app_installation_id_app_installation"),
        "location",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_location_created_by_app_installation_id_app_installation"),
        "location",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "oauth2_client", sa.Column("admin_unit_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "oauth2_client",
        sa.Column("app_permissions", flask_security.datastore.AsaList(), nullable=True),
    )
    op.add_column(
        "oauth2_client", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("created_by_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("updated_by_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "oauth2_client",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "oauth2_client",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_created_by_id_user"),
        "oauth2_client",
        "user",
        ["created_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_updated_by_app_installation_id_app_installation"),
        "oauth2_client",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_updated_by_id_user"),
        "oauth2_client",
        "user",
        ["updated_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_created_by_app_installation_id_app_installation"),
        "oauth2_client",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_admin_unit_id_adminunit"),
        "oauth2_client",
        "adminunit",
        ["admin_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("oauth2_token", sa.Column("app_id", sa.Integer(), nullable=True))
    op.add_column(
        "oauth2_token", sa.Column("app_installation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_oauth2_token_app_id_oauth2_client"),
        "oauth2_token",
        "oauth2_client",
        ["app_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_token_app_installation_id_app_installation"),
        "oauth2_token",
        "app_installation",
        ["app_installation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "settings",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "settings",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_settings_updated_by_app_installation_id_app_installation"),
        "settings",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_settings_created_by_app_installation_id_app_installation"),
        "settings",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    op.alter_column("oauth2_client", "user_id", nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_settings_created_by_app_installation_id_app_installation"),
        "settings",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_settings_updated_by_app_installation_id_app_installation"),
        "settings",
        type_="foreignkey",
    )
    op.drop_column("settings", "updated_by_app_installation_id")
    op.drop_column("settings", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_oauth2_token_app_installation_id_app_installation"),
        "oauth2_token",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_oauth2_token_app_id_oauth2_client"), "oauth2_token", type_="foreignkey"
    )
    op.drop_column("oauth2_token", "app_installation_id")
    op.drop_column("oauth2_token", "app_id")
    op.drop_constraint(
        op.f("fk_oauth2_client_admin_unit_id_adminunit"),
        "oauth2_client",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_created_by_app_installation_id_app_installation"),
        "oauth2_client",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_updated_by_id_user"), "oauth2_client", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_updated_by_app_installation_id_app_installation"),
        "oauth2_client",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_created_by_id_user"), "oauth2_client", type_="foreignkey"
    )
    op.drop_column("oauth2_client", "updated_by_app_installation_id")
    op.drop_column("oauth2_client", "created_by_app_installation_id")
    op.drop_column("oauth2_client", "updated_by_id")
    op.drop_column("oauth2_client", "created_by_id")
    op.drop_column("oauth2_client", "updated_at")
    op.drop_column("oauth2_client", "created_at")
    op.drop_column("oauth2_client", "app_permissions")
    op.drop_column("oauth2_client", "admin_unit_id")
    op.drop_constraint(
        op.f("fk_location_created_by_app_installation_id_app_installation"),
        "location",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_location_updated_by_app_installation_id_app_installation"),
        "location",
        type_="foreignkey",
    )
    op.drop_column("location", "updated_by_app_installation_id")
    op.drop_column("location", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_license_created_by_app_installation_id_app_installation"),
        "license",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_license_updated_by_app_installation_id_app_installation"),
        "license",
        type_="foreignkey",
    )
    op.drop_column("license", "updated_by_app_installation_id")
    op.drop_column("license", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_image_created_by_app_installation_id_app_installation"),
        "image",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_image_updated_by_app_installation_id_app_installation"),
        "image",
        type_="foreignkey",
    )
    op.drop_column("image", "updated_by_app_installation_id")
    op.drop_column("image", "created_by_app_installation_id")
    op.drop_constraint(
        op.f(
            "fk_eventreferencerequest_created_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_eventreferencerequest_updated_by_app_installation_id_app_installation"
        ),
        "eventreferencerequest",
        type_="foreignkey",
    )
    op.drop_column("eventreferencerequest", "updated_by_app_installation_id")
    op.drop_column("eventreferencerequest", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventreference_updated_by_app_installation_id_app_installation"),
        "eventreference",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventreference_created_by_app_installation_id_app_installation"),
        "eventreference",
        type_="foreignkey",
    )
    op.drop_column("eventreference", "updated_by_app_installation_id")
    op.drop_column("eventreference", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventplace_updated_by_app_installation_id_app_installation"),
        "eventplace",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventplace_created_by_app_installation_id_app_installation"),
        "eventplace",
        type_="foreignkey",
    )
    op.drop_column("eventplace", "updated_by_app_installation_id")
    op.drop_column("eventplace", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventorganizer_updated_by_app_installation_id_app_installation"),
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventorganizer_created_by_app_installation_id_app_installation"),
        "eventorganizer",
        type_="foreignkey",
    )
    op.drop_column("eventorganizer", "updated_by_app_installation_id")
    op.drop_column("eventorganizer", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_eventlist_created_by_app_installation_id_app_installation"),
        "eventlist",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_eventlist_updated_by_app_installation_id_app_installation"),
        "eventlist",
        type_="foreignkey",
    )
    op.drop_column("eventlist", "updated_by_app_installation_id")
    op.drop_column("eventlist", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_event_updated_by_app_installation_id_app_installation"),
        "event",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_created_by_app_installation_id_app_installation"),
        "event",
        type_="foreignkey",
    )
    op.drop_column("event", "updated_by_app_installation_id")
    op.drop_column("event", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_customwidget_created_by_app_installation_id_app_installation"),
        "customwidget",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_customwidget_updated_by_app_installation_id_app_installation"),
        "customwidget",
        type_="foreignkey",
    )
    op.drop_column("customwidget", "updated_by_app_installation_id")
    op.drop_column("customwidget", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_apikey_created_by_app_installation_id_app_installation"),
        "apikey",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_apikey_updated_by_app_installation_id_app_installation"),
        "apikey",
        type_="foreignkey",
    )
    op.drop_column("apikey", "updated_by_app_installation_id")
    op.drop_column("apikey", "created_by_app_installation_id")
    op.drop_constraint(
        op.f(
            "fk_adminunitverificationrequest_created_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_adminunitverificationrequest_updated_by_app_installation_id_app_installation"
        ),
        "adminunitverificationrequest",
        type_="foreignkey",
    )
    op.drop_column("adminunitverificationrequest", "updated_by_app_installation_id")
    op.drop_column("adminunitverificationrequest", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_adminunitrelation_created_by_app_installation_id_app_installation"),
        "adminunitrelation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunitrelation_updated_by_app_installation_id_app_installation"),
        "adminunitrelation",
        type_="foreignkey",
    )
    op.drop_column("adminunitrelation", "updated_by_app_installation_id")
    op.drop_column("adminunitrelation", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_adminunitinvitation_updated_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunitinvitation_created_by_app_installation_id_app_installation"),
        "adminunitinvitation",
        type_="foreignkey",
    )
    op.drop_column("adminunitinvitation", "updated_by_app_installation_id")
    op.drop_column("adminunitinvitation", "created_by_app_installation_id")
    op.drop_constraint(
        op.f("fk_adminunit_created_by_app_installation_id_app_installation"),
        "adminunit",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_adminunit_updated_by_app_installation_id_app_installation"),
        "adminunit",
        type_="foreignkey",
    )
    op.drop_column("adminunit", "updated_by_app_installation_id")
    op.drop_column("adminunit", "created_by_app_installation_id")
    op.drop_index(op.f("ix_app_key_kid"), table_name="app_key")
    op.drop_table("app_key")
    op.drop_table("app_installation")
    # ### end Alembic commands ###
