"""empty message

Revision ID: b1a6e7630185
Revises: 35a6577b6af8
Create Date: 2021-01-25 11:38:36.483434

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import dbtypes


# revision identifiers, used by Alembic.
revision = "b1a6e7630185"
down_revision = "35a6577b6af8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adminunit",
        sa.Column("incoming_reference_requests_allowed", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("adminunit", "incoming_reference_requests_allowed")
    # ### end Alembic commands ###
