"""empty message

Revision ID: dcd0b71650b0
Revises: 699c4f6a7fe8
Create Date: 2020-07-28 17:10:49.606513

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import dbtypes


# revision identifiers, used by Alembic.
revision = "dcd0b71650b0"
down_revision = "699c4f6a7fe8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eventorganizer", sa.Column("location_id", sa.Integer(), nullable=True)
    )
    op.add_column("eventorganizer", sa.Column("logo_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "eventorganizer", "image", ["logo_id"], ["id"])
    op.create_foreign_key(None, "eventorganizer", "location", ["location_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "eventorganizer", type_="foreignkey")
    op.drop_constraint(None, "eventorganizer", type_="foreignkey")
    op.drop_column("eventorganizer", "logo_id")
    op.drop_column("eventorganizer", "location_id")
    # ### end Alembic commands ###
