"""empty message

Revision ID: dddeceadde74
Revises: 31b60d93351d
Create Date: 2020-12-30 16:44:29.013647

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import dbtypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dddeceadde74"
down_revision = "31b60d93351d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("event", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "event",
        "start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event",
        "start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column("event", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
