"""empty message

Revision ID: e1e8c14de66e
Revises: 39c10788ec62
Create Date: 2025-09-06 15:36:01.969732

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "e1e8c14de66e"
down_revision = "39c10788ec62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth2_client", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("created_by_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "oauth2_client", sa.Column("updated_by_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "oauth2_client",
        sa.Column("created_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "oauth2_client",
        sa.Column("updated_by_app_installation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_updated_by_app_installation_id_app_installation"),
        "oauth2_client",
        "app_installation",
        ["updated_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_created_by_id_user"),
        "oauth2_client",
        "user",
        ["created_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_updated_by_id_user"),
        "oauth2_client",
        "user",
        ["updated_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_oauth2_client_created_by_app_installation_id_app_installation"),
        "oauth2_client",
        "app_installation",
        ["created_by_app_installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_oauth2_client_created_by_app_installation_id_app_installation"),
        "oauth2_client",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_updated_by_id_user"), "oauth2_client", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_created_by_id_user"), "oauth2_client", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_oauth2_client_updated_by_app_installation_id_app_installation"),
        "oauth2_client",
        type_="foreignkey",
    )
    op.drop_column("oauth2_client", "updated_by_app_installation_id")
    op.drop_column("oauth2_client", "created_by_app_installation_id")
    op.drop_column("oauth2_client", "updated_by_id")
    op.drop_column("oauth2_client", "created_by_id")
    op.drop_column("oauth2_client", "updated_at")
    op.drop_column("oauth2_client", "created_at")
    # ### end Alembic commands ###
