"""empty message

Revision ID: ff654866893f
Revises: a626456fc25e
Create Date: 2025-05-17 18:11:07.175262

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from project import dbtypes

# revision identifiers, used by Alembic.
revision = "ff654866893f"
down_revision = "a626456fc25e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apikey",
        sa.Column(
            "rate_limit_value",
            sa.String(length=255),
            server_default="500/hour",
            nullable=False,
        ),
    )
    op.add_column(
        "oauth2_client",
        sa.Column(
            "rate_limit_value",
            sa.String(length=255),
            server_default="5000/hour",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_client", "rate_limit_value")
    op.drop_column("apikey", "rate_limit_value")
    # ### end Alembic commands ###
